// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL = port 5432 direct connection (required for migrations)
    // DATABASE_URL = port 6543 transaction pooler (used at runtime via adapter)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"]!,
  },
});
