ALTER TABLE "Tenant" ADD COLUMN "gdprEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Appointment" ADD COLUMN "reminderOptOut" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Appointment" ADD COLUMN "consentGivenAt" TIMESTAMP(3);
